services:

  db:
    image: mysql
    container_name: ${CLIENTE}_db
    hostname: ${CLIENTE}_db
    environment:
      LANG: pt_BR.UTF-8
      TZ: America/Sao_Paulo
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    restart: always
    volumes:
      - db-var-lib-mysql:/var/lib/mysql
      - db-var-log:/var/log
    networks:
      - net0

  gateways:
    image: matheusprotzen/gateways-mock
    container_name: ${CLIENTE}_gateways
    hostname: ${CLIENTE}_gateways
    restart: always
    networks:
      - net0
    ports:
      - 3001:3001
      - 3002:3002

  app:
    build:
      dockerfile: ./app/Dockerfile
    container_name: ${CLIENTE}_app
    hostname: ${CLIENTE}_app
    depends_on:
      - db
      - gateways
    restart: always
    working_dir: /var/www
    volumes:
      - ./www:/var/www
        # - ./app/root:/var/www/app
      - app-var-log:/var/log
    networks:
      - net0
    ports:
      - ${APP_PORT}:80

volumes:
  db-var-lib-mysql:
  db-var-log:
  app-var-log:

networks:
  net0:
    driver: bridge
